version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
