openapi: 3.0.0
info:
  title: Uber Clone API
  description: API para o sistema de mobilidade Uber Clone
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
paths:
  /auth/login:
    post:
      summary: Autenticação de usuário
      description: Realiza o login de um usuário (passageiro ou motorista)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: usuario@exemplo.com
                password:
                  type: string
                  example: senha123
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  /rides:
    post:
      summary: Solicitar uma corrida
      description: Permite que um passageiro solicite uma corrida
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  example: Av. Paulista, 1000 - São Paulo, SP
      responses:
        '201':
          description: Corrida solicitada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 12345
                  status:
                    type: string
                    example: pending
  /users:
    get:
      summary: Listar usuários
      description: Retorna uma lista de todos os usuários (passageiros e motoristas)
      responses:
        '200':
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 12345
                    name:
                      type: string
                      example: João Silva
                    email:
                      type: string
                      example: joao@exemplo.com
                    type:
                      type: string
                      example: passenger
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT